# Generated by Django 5.1.4 on 2024-12-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_assessmentplan_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentplan',
            name='topicsovered',
            field=models.TextField(),
        ),
    ]
