# Generated by Django 5.1.4 on 2024-12-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_assessmentplan_topicsovered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
