# Generated by Django 5.1.4 on 2024-12-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_rename_topicsovered_assessmentplan_topicscoverd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
