# Generated by Django 5.1.4 on 2024-12-16 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_assessmentplan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentplan',
            old_name='id',
            new_name='uid',
        ),
    ]
