# Generated by Django 5.1.4 on 2024-12-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_rename_id_assessmentplan_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentplan',
            old_name='uid',
            new_name='id',
        ),
    ]
