# Generated by Django 5.1.4 on 2024-12-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_alter_assessmentplan_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assessmentplan',
            table='AssessmentPlan1',
        ),
    ]
